version: "3.8"

services:
  generator:
    build: ./generator
    container_name: generator
    volumes:
      - app-data:/app-data
    restart: unless-stopped

  classifier:
    build: ./classifier
    container_name: classifier
    volumes:
      - app-data:/app-data
    depends_on:
      - generator
    restart: unless-stopped

  storage_service:
    build: ./storage_service
    container_name: storage_service
    volumes:
      - app-data:/app-data
    ports:
      - "5000:5000"  # mapeamos el puerto del contenedor al host
    depends_on:
      - classifier
    restart: unless-stopped

volumes:
  app-data:
